

// export const AUTH = 'AUTH';


export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";



export const EMPLOYEEMYDETAIL_REQUEST = 'EMPLOYEEMYDETAIL_REQUEST';
export const EMPLOYEEMYDETAIL_SUCESS = 'EMPLOYEEMYDETAIL_SUCESS';
export const EMPLOYEEMYDETAIL_FAIL = 'EMPLOYEEMYDETAIL_FAIL';


export const LOGOUT = 'LOGOUT';


